### PR TITLE
Support for translating PDF files

### PR DESCRIPTION
**Pull request by dietrichson**
First go at [#84]

### CODE REVIEW

**Comment by MarkEdmondson1234** [comment]
Looking good so far!

**Comment by MarkEdmondson1234** [comment]
Is it ready for review?

**Comment by dietrichson** [comment]
By all means.

You'll notice in the code that I am using v3 of the API whose syntax is
somewhat different from v2 on which gl_translate is based.

**Comment by MarkEdmondson1234** [comment]
Looking good! May I suggest a test is added using the test PDF you have added?

**Comment by dietrichson** [comment]
@MarkEdmondson1234, I added a test. It runs (and passes) manually on my local system, however, there may be an issue regarding v2 and v3 of the API that I am not accounting for. Please check/test on your side as well to verify.

**Comment by dietrichson** [comment]
Two commits for pdf-based testing

**Comment by LukasWallrich** [comment]
Also, some files require shadow text removal for the translation to be of any use - that would be a good option to expose as well (or set as a default, based on my understanding it shouldn't do any harm)

**Comment by MarkEdmondson1234** [comment]
I'm sorry I missed the pull, merged it

**Pull request merged**
