### PR TITLE
added the check for file size

### PR DESCRIPTION
**Pull request by muschellij2**
Got 400 error from https://stackoverflow.com/questions/51601697/invalid-argument-request-payload-size-exceeds-the-limit-10485760-bytes.  Added a simple check on the file size for the request.

### CODE REVIEW

**Comment by MarkEdmondson1234** [comment]
Thanks! But won’t this affect people who are not in the free trial and so limit those users who can go over the limit?  Or is this a hard limit for all users?


________________________________

**Comment by muschellij2** [comment]
I don't know it's a hard limit for all users, but I have a dev account and
getting this limit with my API authorized.
Best,
John

**Comment by MarkEdmondson1234** [comment]
@muschellij2 are you on a trail billing period with GCP? (Just based off the SO answer that indicates this is a factor)

**Comment by muschellij2** [comment]
I do not know, but I've been using it for > 1 month, so I don't think on
trial billing.

Best,
John

**Comment by MarkEdmondson1234** [comment]
Yes creating a branch for pull requests is best, I think library(usethis) has a helper function.


________________________________

**Comment by muschellij2** [comment]
OK - it'll be at least a week or 2 I believe.

Best,
John

**Comment by MarkEdmondson1234** [comment]
Sorry it took so long ot merge, but pushing for a CRAN release now @muschellij2 - I've added a credit to you in the description, thanks a lot for the pull requests.

**Comment by muschellij2** [comment]
Any time - thanks for the great package.  Totally forgot about this one

**Pull request merged**
