### PR TITLE
updated gl_auth for gl_auto_auth

### PR DESCRIPTION
**Pull request by muschellij2**
So importing `googleLanguageR` vs. using `library(googleLanguageR)` the `.onAttach` gets called in the latter case.  I think if you can invoke in code would be useful.  I wasn't sure whether to use `gar_auto_auth` or `gar_attach_auto_auth`, but it seems like the latter is the behavior desired.

So added `gl_auto_auth`, should achieve this.

### CODE REVIEW

**Comment by MarkEdmondson1234** [comment]
Thanks for the contribution :)  Could I get a bit more detail what need this solves for you here?  It was a decision to only use service accounts as this is a paid for service and could generate confusion using OAuth2 user authentication, but is that something you wanted to do?

**Comment by muschellij2** [comment]
Don't want OAuth, but be able to run a command `gl_auto_auth` that looks same places as `gar_auto_auth` (such as `GAR_AUTH_FILE`) so `googleLanguageR` doesn't need to be attached, but same behavior can be achieved as if you did attach it (as it calls `gar_attach_auto_auth`)

**Comment by MarkEdmondson1234** [comment]
Ok cool makes sense - would you mind adding some documentation and examples to the function (usually in a \dontrun) so it will update the website reference for any questions about it in the future?  I'll then merge.

**Comment by muschellij2** [comment]
The docs are done and fixed `DESCRIPTION` and `httptest` package requirement in Suggests for test.

**Comment by MarkEdmondson1234** [comment]
Great thanks!

**Pull request merged**
